[project]
name = "ds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bokeh>=3.4.3",
    "jupyter>=1.1.1",
    "pandas>=2.3.0",
]
